#!/bin/bash
# run_m3rtt2.sh <svm16|svm32|kvm>
# M3 RTT sweep, RTT range 0.1-2ms only (realistic TCP: datacenter to cross-DC).
#   RTT = 100us (loopback) + 2*delay;  delay 0/50/200/450/950us
#   fio: randrw(70/30) bs=4k numjobs=1 iodepth=32 60s direct=1
# svm16/svm32: SVM t0 (W=4,I=32) with batch_n=16/32, 5 points x 2 runs
# kvm: local virtio-blk (no TCP, RTT-independent) baseline, 0.1/2ms x 1 run
set -u
MODE=$1
H=/home/waiai/svm
CONF=$H/local_qemu/hw/virtio-remote/vr.conf
BASE=$H/exp/results/m3rtt2
OUT=$BASE/$MODE
mkdir -p $OUT
SSH="DISPLAY=:0 SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=/tmp/askpass.sh ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ServerAliveInterval=10 -p 2222 wai@127.0.0.1"
TC() { echo dxeqqghk | sudo -S tc "$@" >/dev/null 2>&1; }
LABELS=(0p1ms 0p2ms 0p5ms 1ms 2ms)
DELAYS=(0 50 200 450 950)
FIO="echo wai | sudo -S fio --name=M3RTT --filename=/dev/vdb --rw=randrw --rwmixread=70 --bs=4k --numjobs=1 --iodepth=32 --ioengine=libaio --direct=1 --runtime=60 --time_based --group_reporting --output-format=json"

wait_ssh() {
  for i in $(seq 1 60); do
    if env $SSH "true" 2>/dev/null; then echo "  SSH up after $i tries"; return 0; fi
    sleep 3
  done
  echo "  SSH FAILED"; exit 1
}

start_svm() {
  local B=$1
  cat > $CONF <<EOF
# SVM M3RTT mode=$MODE batch=$B (generated by run_m3rtt2.sh)
buf_pool=0
inflight_size=32
local_batch_n=$B
stub_batch_n=$B
zc_send_min=1048576
workers=4
EOF
  pkill -f "remote-stub" 2>/dev/null; pkill -f "qemu-system-x86_64" 2>/dev/null; sleep 2
  setsid remote-stub \
    -smp 4 \
    -drive file=$H/exp/remote/fio.raw,if=none,id=drive1,format=raw,cache=none \
    -device virtio-blk-pci,drive=drive1,serial=data-disk,remote-stub=127.0.0.1@5552 \
    -display none -monitor none -serial file:/tmp/stub-blk.log \
    > /tmp/stub-out.log 2>&1 < /dev/null &
  setsid $H/local_qemu/build/qemu-system-x86_64 \
    -enable-kvm -cpu host -smp 4 -m 4096 \
    -drive file=$H/exp/local/system.raw,if=none,id=drive0,format=raw \
    -device virtio-blk-pci,drive=drive0 \
    -netdev user,id=net0,hostfwd=tcp::2222-:22 \
    -device virtio-net-pci,netdev=net0 \
    -drive file=$H/exp/local/svm/dummy.raw,if=none,id=drive1,format=raw \
    -device virtio-blk-pci,drive=drive1,serial=data-disk,remote-machine=127.0.0.1@5552 \
    -serial file:guest.log -monitor none -display none \
    -qmp unix:/tmp/qmp.sock,server,nowait \
    > /tmp/local-out.log 2>&1 < /dev/null &
  wait_ssh
}

start_kvm() {
  pkill -f "remote-stub" 2>/dev/null; pkill -f "qemu-system-x86_64" 2>/dev/null; sleep 2
  setsid $H/local_qemu/build/qemu-system-x86_64 \
    -enable-kvm -cpu host -smp 4 -m 4096 \
    -drive file=$H/exp/local/system.raw,if=none,id=drive0,format=raw,cache=none \
    -device virtio-blk-pci,drive=drive0,bootindex=1 \
    -netdev user,id=net0,hostfwd=tcp::2222-:22 \
    -device virtio-net-pci,netdev=net0 \
    -drive file=$H/exp/remote/fio.raw,if=none,id=drive1,format=raw,cache=none \
    -device virtio-blk-pci,drive=drive1,serial=data-disk \
    -serial file:/tmp/kvm-guest.log -monitor none -display none \
    -qmp unix:/tmp/qmp.sock,server,nowait \
    > /tmp/kvm-local-out.log 2>&1 < /dev/null &
  wait_ssh
}

echo "=== [$(date +%T)] M3RTT2 mode=$MODE: start ==="
case $MODE in
  svm16) start_svm 16 ;;
  svm32) start_svm 32 ;;
  kvm)   start_kvm ;;
  *) echo "bad mode $MODE"; exit 1 ;;
esac

# KVM baseline: no TCP, no netem needed; run 0.1ms + 2ms as flat-line proof
if [ "$MODE" = "kvm" ]; then
  for lbl in 0p1ms 2ms; do
    echo "### [$(date +%T)] KVM $lbl (no netem, RTT-independent)"
    for r in 1; do
      env $SSH "$FIO" 2>/dev/null > $OUT/rtt_${lbl}_r$r.json
      python3 -c "
import json
raw=open('$OUT/rtt_${lbl}_r$r.json').read()
d,_=json.JSONDecoder().raw_decode(raw)
j=d['jobs'][0]; rd=j['read']; wr=j['write']
print(f'  KVM $lbl r$r: r={rd[\"iops\"]:.0f} w={wr[\"iops\"]:.0f} tot={rd[\"iops\"]+wr[\"iops\"]:.0f}')
"
    done
  done
else
  for i in ${!DELAYS[@]}; do
    d=${DELAYS[$i]}; lbl=${LABELS[$i]}
    TC qdisc del dev lo root 2>/dev/null
    if [ $d -gt 0 ]; then
      TC qdisc add dev lo root netem delay ${d}us || { echo "TC_FAIL $lbl"; exit 2; }
    fi
    echo "### [$(date +%T)] SVM($MODE) RTT $lbl (delay ${d}us)"
    for r in 1 2; do
      env $SSH "$FIO" 2>/dev/null > $OUT/rtt_${lbl}_r$r.json
      python3 -c "
import json
raw=open('$OUT/rtt_${lbl}_r$r.json').read()
d,_=json.JSONDecoder().raw_decode(raw)
j=d['jobs'][0]; rd=j['read']; wr=j['write']
print(f'  $lbl r$r: r={rd[\"iops\"]:.0f} w={wr[\"iops\"]:.0f} tot={rd[\"iops\"]+wr[\"iops\"]:.0f} clat={rd[\"clat_ns\"][\"mean\"]/1000:.0f}us')
"
    done
  done
  TC qdisc del dev lo root 2>/dev/null
fi

# teardown
env $SSH "echo wai | sudo -S poweroff" 2>/dev/null
sleep 6
pkill -f "qemu-system-x86_64" 2>/dev/null
pkill -f "remote-stub" 2>/dev/null
echo "M3RTT2_${MODE}_OK [$(date +%T)]"
